// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAU03aLImyw6ifs9yaVTf22STWI_fyiLU',
    appId: '1:945939579577:web:d72e2458737e200affd168',
    messagingSenderId: '945939579577',
    projectId: 'insta-22729',
    authDomain: 'insta-22729.firebaseapp.com',
    storageBucket: 'insta-22729.appspot.com',
    measurementId: 'G-XHFD0NHFPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQJsY5OogaRxHtH4rF4HjrqCDZnDamsAw',
    appId: '1:945939579577:android:6929d28826bd5e74ffd168',
    messagingSenderId: '945939579577',
    projectId: 'insta-22729',
    storageBucket: 'insta-22729.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw0UxuXv90_H_lE634zbBMOh8FxSKJ-Uc',
    appId: '1:945939579577:ios:841f7b332d928b68ffd168',
    messagingSenderId: '945939579577',
    projectId: 'insta-22729',
    storageBucket: 'insta-22729.appspot.com',
    iosClientId: '945939579577-csv4g3f494qddsbdanhitdlenmnj45ln.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw0UxuXv90_H_lE634zbBMOh8FxSKJ-Uc',
    appId: '1:945939579577:ios:841f7b332d928b68ffd168',
    messagingSenderId: '945939579577',
    projectId: 'insta-22729',
    storageBucket: 'insta-22729.appspot.com',
    iosClientId: '945939579577-csv4g3f494qddsbdanhitdlenmnj45ln.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );
}
